--exemplo de extração de foto de campanha em diferentes situações

SET NOCOUNT ON

DECLARE @DATA_INI_RCP AS DATETIME
DECLARE @CAMPANHA_ID_INI AS INT
--DECLARE @LISTA_ID AS INT

SET @DATA_INI_RCP = '2019-01-01' -- DEFINIR DATA INICIAL PARA EXTRACAO DO RECEPTIVO
SET @CAMPANHA_ID_INI = 16423 -- >>> MENOR CAMPANHA 2019 <<< -- DEFINIR AQUI CAMPANHA INICIAL PARA EXTRACAO DO ATIVO
--SET @LISTA_ID = 5377 -- LISTA_ID VINCULADA ÀS CAMPANHAS ANALISADAS

IF OBJECT_ID('TEMPDB.DBO.#PRE','U') IS NOT NULL
 DROP TABLE #PRE;

SELECT EVENTO.MAILING_ID, COUNT(EVENTO.MAILING_ID) AS QTDE_CONTRATACOES, SUM(EA1.CAMPO_VALOR) AS TOTAL_PRÊMIO
INTO #PRE
FROM EVENTO
	INNER JOIN TIPO_PROCESSO (NOLOCK)   ON (EVENTO.TIPO_PROCESSO_ID = TIPO_PROCESSO.TIPO_PROCESSO_ID)
	INNER JOIN BV_RELAGRUPAMENTO    ON (TIPO_PROCESSO.RELATORIO_AGRUPAMENTO = BV_RELAGRUPAMENTO.BV_RELAGRUPAMENTO_ID)
	LEFT JOIN EVENTO_AUX EA1 (NOLOCK) ON (EVENTO.EVENTO_ID = EA1.EVENTO_ID AND EA1.CAMPO_AUX_ID IN (SELECT CAMPO_AUX_ID FROM CAMPO_AUX WHERE CODIGO IN ('PRMBRUTO','104002'))) -- PREMIO
WHERE EVENTO.ORIGEM_ID IN (576,577,593)
	AND EVENTO.CAMPANHA_ID > @CAMPANHA_ID_INI
	AND BV_RELAGRUPAMENTO.BV_RELAGRUPAMENTO IN ('RECUPERADO')
	AND EVENTO.EVENTO_ID <> 194261384
	AND EA1.CAMPO_VALOR IS NOT NULL
GROUP BY EVENTO.MAILING_ID

IF OBJECT_ID('TEMPDB.DBO.#OPE','U') IS NOT NULL
 DROP TABLE #OPE;
SELECT
 EVENTO.EVENTO_ID, OPERADOR.OPERADOR_NAME, EQUIPE.EQUIPE
INTO #OPE
FROM
 EVENTO (NOLOCK)
	 INNER JOIN OPERADOR (NOLOCK) ON EVENTO.OPERADOR_ID = OPERADOR.OPERADOR_ID
	 INNER JOIN EQUIPE (NOLOCK) ON EVENTO.EQUIPE_ID = EQUIPE.EQUIPE_ID
	 INNER JOIN MAILING (NOLOCK) ON EVENTO.MAILING_ID = MAILING.MAILING_ID
	 INNER JOIN CAMPANHA (NOLOCK) ON EVENTO.CAMPANHA_ID = CAMPANHA.CAMPANHA_ID
WHERE
	MAILING.ORIGEM_ID IN (576,577,593) -- ORIGENS CREDITO PROTEGIDO - TODAS
   AND MAILING.CAMPANHA_ID >= @CAMPANHA_ID_INI --12370 -- MENOR CAMPANHA_ID DE 2018
   AND MAILING.TIPO_PROCESSO_ID NOT IN (0,8959,8991,9060) -- NÃO CONTATADO, BLOQUEIO DE PARCELAS BAIXADAS E LEADS DUPLICADOS
   AND CAMPANHA.ATIVO = 1

IF OBJECT_ID('TEMPDB.DBO.#PROD','U') IS NOT NULL
 DROP TABLE #PROD;
SELECT  CASE 
   WHEN #PRE.TOTAL_PRÊMIO IS NOT NULL THEN 'CONTRATADO'
   WHEN #TB.AGRUPAMENTO IN ('CANCELA E RECONTRATA','RENOVAÇÃO','CONTRATAÇÃO','RECUPERADO') THEN 'CONTRATADO'
   WHEN #TB.AGRUPAMENTO IN ('CONSULTA SISTEMA','RECUSA','NÃO RECUPERADO','RECUSA DO SEGURADO','SEM ACEITAÇÃO PELA SEGURADORA') THEN 'NÃO CONTRATADO'
   WHEN #TB.AGRUPAMENTO IN ('OCORRÊNCIA PRODUTIVA','INDICAÇÃO','SOLICITACAO ENDOSSO','ABERTURA DE PROCESSO') THEN 'OUTROS'
   WHEN #TB.AGRUPAMENTO IN ('SOLICITACAO COTACAO','AGENDAMENTO CALL CENTER','RESULTADO DE TELEFONIA','AGENDAMENTO CLIENTE CONTATADO','AGENDAMENTO CLIENTE NÃO CONTATADO') THEN 'CLIENTE AGENDADO'
   WHEN #TB.AGRUPAMENTO IN ('EXCLUSÃO SISTEMA') THEN 'EXCLUSÃO DUPLICIDADE'
  ELSE 'NÃO TRABALHADO'
  END AS STATUS,
  'CREDPRT_RECUP_ATIVO' AS [OPERACAO],
  TIPO_ORIGEM.TIPO_ORIGEM AS [TIPO_CANAL],
  ORIGEM.ORIGEM AS [CANAL CONTATO],
  #TB.*,
  ISNULL(CASE WHEN #PRE.TOTAL_PRÊMIO IS NULL THEN CONVERT(FLOAT,EA1.CAMPO_VALOR) ELSE CONVERT(FLOAT,#PRE.TOTAL_PRÊMIO) END,0) AS [PREMIO],
  REPLACE(EA2.CAMPO_TXT,' ','') AS [PROPOSTA],
  CASE WHEN #TB.AGRUPAMENTO IN ('AGENDAMENTO CLIENTE NÃO CONTATADO','RECUSA SEM CONTATO','RESULTADO DE TELEFONIA') THEN 'NÃO'
  WHEN #TB.AGRUPAMENTO IN ('REGISTRO LIVRE','INDICAÇÃO','CONSULTA SISTEMA','SOLUÇÃO','OCORRÊNCIA','OCORRÊNCIA PRODUTIVA','NÃO CLASSIFICADO','NÃO CONTATADO')
  THEN '' ELSE 'SIM' END AS [CPC],
  CASE WHEN #PRE.TOTAL_PRÊMIO IS NOT NULL THEN #PRE.QTDE_CONTRATACOES
  WHEN EA1.CAMPO_VALOR IS NOT NULL THEN 1 ELSE 0 END AS [QTDE_CONTRATACOES]

INTO #PROD
FROM
(
SELECT DISTINCT(MAILING.MAILING_ID) AS MAILING_ID,
    MAX(EVENTO.EVENTO_ID) AS EVENTO_ID,
    EVENTO.ORIGEM_ID,
    MAILING.CLIENTE_ID,
    LISTA_DET.INT_AUX4 AS PUBLICO,
    --LISTA_DET_AUX.TXT_AUX10 AS RESTRICAO, 
    CLIENTE.NOME,
    CASE WHEN CLIENTE.CPF = '___.___.___-__' THEN CLIENTE.CGC ELSE CLIENTE.CPF END AS CPF_CNPJ,
    YEAR(MAILING.DATA_STATUS) AS ANO_RESULTADO,
    MONTH(MAILING.DATA_STATUS) AS MES_RESULTADO,
    DAY(MAILING.DATA_STATUS) AS DIA_RESULTADO,
    SUBSTRING(CAMPANHA.CAMPANHA_COD,1,4) AS ANO_IMPORTACAO,
    SUBSTRING(CAMPANHA.CAMPANHA_COD,6,2) AS MES_IMPORTACAO,
    SUBSTRING(CAMPANHA.CAMPANHA_COD,9,2) AS DIA_IMPORTACAO,
    CASE WHEN MAILING.TIPO_PROCESSO_ID = 0 THEN 'NÃO CONTATADO' 
   ELSE BV_RELAGRUPAMENTO.BV_RELAGRUPAMENTO 
  END AS AGRUPAMENTO,
       CASE WHEN MAILING.TIPO_PROCESSO_ID = 0 THEN 'NÃO CONTATADO' 
   WHEN TIPO_PROCESSO.COD_FIM = 6100 THEN 'OUTROS'
   ELSE TIPO_PROCESSO.TITULO 
  END AS FINALIZACAO,
  --OP.OPERADOR_NAME,
  --OP.EQUIPE,
  LISTA.LISTA,
  CAMPANHA.CAMPANHA,
  '1' AS QTDE,
  CASE 
   WHEN LISTA_DET_AUX.TXT_AUX01 < 1000 THEN '13 - R$ - ABAIXO DE 1K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 1000 AND 1999 THEN '12 - R$ - 1K À 2K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 2000 AND 2999 THEN '11 - R$ - 2K À 3K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 3000 AND 3999 THEN '10 - R$ - 3K À 4K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 4000 AND 4999 THEN '09 - R$ - 4K À 5K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 5000 AND 5999 THEN '08 - R$ - 5K À 6K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 6000 AND 6999 THEN '07 - R$ - 6K À 7K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 7000 AND 7999 THEN '06 - R$ - 7K À 8K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 8000 AND 8999 THEN '05 - R$ - 8K À 9K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 9000 AND 11999 THEN '04 - R$ - 9K À 12K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 12000 AND 14999 THEN '03 - R$ - 12K À 15K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 15000 AND 19999 THEN '02 - R$ - 15K À 20K'
   WHEN LISTA_DET_AUX.TXT_AUX01 > 20000 THEN '01 - R$ - ACIMA DE 20K'
   ELSE '14 - N/A'
  END AS [FAIXA_PREMIO_MAILING],
  LISTA_DET_AUX.TXT_AUX01 AS [PREMIO_MAILING]
                 
FROM MAILING
	LEFT JOIN EVENTO (NOLOCK)    ON (MAILING.MAILING_ID = EVENTO.MAILING_ID AND MAILING.TIPO_PROCESSO_ID = EVENTO.TIPO_PROCESSO_ID AND MAILING.ORIGEM_ID = EVENTO.ORIGEM_ID)
	INNER JOIN CLIENTE (NOLOCK)    ON (EVENTO.CLIENTE_ID = CLIENTE.CLIENTE_ID)
	INNER JOIN LISTA (NOLOCK)    ON (MAILING.LISTA_ID = LISTA.LISTA_ID)
	INNER JOIN LISTA_DET (NOLOCK)   ON (MAILING.MAILING_ID = LISTA_DET.MAILING_ID)
	INNER JOIN LISTA_DET_AUX (NOLOCK)  ON (LISTA_DET.LISTA_DET_ID = LISTA_DET_AUX.LISTA_DET_ID)
	--LEFT JOIN #OPE AS OP ON (EVENTO.EVENTO_ID = OP.EVENTO_ID)
	LEFT JOIN TIPO_PROCESSO (NOLOCK)  ON (MAILING.TIPO_PROCESSO_ID = TIPO_PROCESSO.TIPO_PROCESSO_ID)
	--LEFT JOIN OPERADOR (NOLOCK)    ON (EVENTO.OPERADOR_ID = OPERADOR.OPERADOR_ID)
	--LEFT JOIN EQUIPE (NOLOCK)    ON (OPERADOR.EQUIPE_ID = EQUIPE.EQUIPE_ID)
	INNER JOIN CAMPANHA (NOLOCK)   ON (MAILING.CAMPANHA_ID = CAMPANHA.CAMPANHA_ID)
	LEFT JOIN BV_RELAGRUPAMENTO (NOLOCK) ON (TIPO_PROCESSO.RELATORIO_AGRUPAMENTO = BV_RELAGRUPAMENTO.BV_RELAGRUPAMENTO_ID)

WHERE MAILING.ORIGEM_ID IN (576,577,593) -- ORIGENS CREDITO PROTEGIDO - TODAS
	AND MAILING.CAMPANHA_ID > @CAMPANHA_ID_INI --12370 -- MENOR CAMPANHA_ID DE 2018
	AND MAILING.TIPO_PROCESSO_ID NOT IN (0,8959,8991,9060) -- NÃO CONTATADO, BLOQUEIO DE PARCELAS BAIXADAS E LEADS DUPLICADOS
	AND CAMPANHA.ATIVO = 1
	--AND MAILING.ORIGEM_ID NOT IN (701,839,874,875,878,898)


GROUP BY MAILING.MAILING_ID, MAILING.CLIENTE_ID,CLIENTE.NOME,CLIENTE.CPF, CLIENTE.CGC,
    DATA_STATUS, CAMPANHA.CAMPANHA_COD, BV_RELAGRUPAMENTO.BV_RELAGRUPAMENTO, MAILING.TIPO_PROCESSO_ID, 
    TIPO_PROCESSO.COD_FIM,TIPO_PROCESSO.TITULO,/*OP.OPERADOR_NAME,OP.EQUIPE, */
    LISTA_DET.INT_AUX4,LISTA_DET_AUX.TXT_AUX10,
    CAMPANHA.CAMPANHA,EVENTO.ORIGEM_ID, LISTA.LISTA, LISTA_DET_AUX.TXT_AUX01

UNION ALL 

SELECT '' AS MAILING_ID,
    '' AS EVENTO_ID,
    MAILING.ORIGEM_ID,    
    '' AS CLIENTE_ID,
    LISTA_DET.INT_AUX4 AS PUBLICO,
    --LISTA_DET_AUX.TXT_AUX10 AS RESTRICAO,    
    '' AS NOME,
    '' AS CPF_CNPJ,
    CASE WHEN MAILING.TIPO_PROCESSO_ID = 0
   THEN SUBSTRING(CAMPANHA.CAMPANHA_COD,1,4)
   ELSE YEAR(MAILING.DATA_STATUS)
    END AS ANO_RESULTADO,
       CASE WHEN MAILING.TIPO_PROCESSO_ID = 0
   THEN SUBSTRING(CAMPANHA.CAMPANHA_COD,6,2)
   ELSE MONTH(MAILING.DATA_STATUS)
    END AS MES_RESULTADO,
    CASE WHEN MAILING.TIPO_PROCESSO_ID = 0
   THEN SUBSTRING(CAMPANHA.CAMPANHA_COD,9,2)
   ELSE DAY(MAILING.DATA_STATUS)
    END AS DIA_RESULTADO,
    SUBSTRING(CAMPANHA.CAMPANHA_COD,1,4) AS ANO_IMPORTACAO,
    SUBSTRING(CAMPANHA.CAMPANHA_COD,6,2) AS MES_IMPORTACAO,
    SUBSTRING(CAMPANHA.CAMPANHA_COD,9,2) AS DIA_IMPORTACAO,
    CASE WHEN MAILING.TIPO_PROCESSO_ID = 0 THEN 'NÃO CONTATADO' 
   ELSE BV_RELAGRUPAMENTO.BV_RELAGRUPAMENTO 
  END AS AGRUPAMENTO,
       CASE WHEN MAILING.TIPO_PROCESSO_ID = 0 THEN 'NÃO CONTATADO' 
   WHEN TIPO_PROCESSO.COD_FIM = 6100 THEN 'OUTROS'
   ELSE TIPO_PROCESSO.TITULO 
  END AS FINALIZACAO,
  --'SEM CONTATO' AS OPERADOR,
  --'SEM CONTATO' AS EQUIPE,
  LISTA.LISTA,
  CAMPANHA.CAMPANHA,
  COUNT(MAILING.MAILING_ID) AS QTDE,
  CASE 
   WHEN LISTA_DET_AUX.TXT_AUX01 < 1000 THEN '13 - R$ - ABAIXO DE 1K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 1000 AND 1999 THEN '12 - R$ - 1K À 2K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 2000 AND 2999 THEN '11 - R$ - 2K À 3K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 3000 AND 3999 THEN '10 - R$ - 3K À 4K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 4000 AND 4999 THEN '09 - R$ - 4K À 5K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 5000 AND 5999 THEN '08 - R$ - 5K À 6K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 6000 AND 6999 THEN '07 - R$ - 6K À 7K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 7000 AND 7999 THEN '06 - R$ - 7K À 8K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 8000 AND 8999 THEN '05 - R$ - 8K À 9K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 9000 AND 11999 THEN '04 - R$ - 9K À 12K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 12000 AND 14999 THEN '03 - R$ - 12K À 15K'
   WHEN LISTA_DET_AUX.TXT_AUX01 BETWEEN 15000 AND 19999 THEN '02 - R$ - 15K À 20K'
   WHEN LISTA_DET_AUX.TXT_AUX01 > 20000 THEN '01 - R$ - ACIMA DE 20K'
   ELSE '14 - N/A'
  END AS [FAIXA_PREMIO_MAILING],
  LISTA_DET_AUX.TXT_AUX01 AS [PREMIO_MAILING]
  
FROM MAILING
	INNER JOIN LISTA (NOLOCK)    ON (MAILING.LISTA_ID = LISTA.LISTA_ID)
	INNER JOIN LISTA_DET     ON (MAILING.MAILING_ID = LISTA_DET.MAILING_ID)
	INNER JOIN LISTA_DET_AUX    ON (LISTA_DET.LISTA_DET_ID = LISTA_DET_AUX.LISTA_DET_ID)
	LEFT JOIN TIPO_PROCESSO     ON (MAILING.TIPO_PROCESSO_ID = TIPO_PROCESSO.TIPO_PROCESSO_ID)
	LEFT JOIN TAB_FIM      ON (TIPO_PROCESSO.COD_FIM = TAB_FIM.COD_FIM)
	INNER JOIN CAMPANHA      ON (MAILING.CAMPANHA_ID = CAMPANHA.CAMPANHA_ID)
	LEFT JOIN BV_RELAGRUPAMENTO    ON (TIPO_PROCESSO.RELATORIO_AGRUPAMENTO = BV_RELAGRUPAMENTO.BV_RELAGRUPAMENTO_ID)

WHERE MAILING.ORIGEM_ID IN (576,577,593) -- ORIGENS CREDITO PROTEGIDO - TODAS
   AND MAILING.CAMPANHA_ID > @CAMPANHA_ID_INI --12370 -- MENOR CAMPANHA_ID DE 2018
   AND MAILING.TIPO_PROCESSO_ID IN (0,8959,8991,9060) -- NÃO CONTATADOS 
   AND CAMPANHA.ATIVO = 1
   --AND MAILING.ORIGEM_ID NOT IN (701,839,874,875,878,898)

GROUP BY DATA_STATUS, CAMPANHA.CAMPANHA_COD, BV_RELAGRUPAMENTO.BV_RELAGRUPAMENTO, MAILING.TIPO_PROCESSO_ID, 
    TIPO_PROCESSO.COD_FIM,TIPO_PROCESSO.TITULO,
    LISTA_DET.INT_AUX4,LISTA_DET_AUX.TXT_AUX10,
    CAMPANHA.CAMPANHA,MAILING.ORIGEM_ID, LISTA.LISTA, LISTA_DET_AUX.TXT_AUX01

UNION ALL 

SELECT '' AS MAILING_ID,
    #TB.EVENTO_ID AS EVENTO_ID,
    EVENTO.ORIGEM_ID,
    EVENTO.CLIENTE_ID,
    0 AS PUBLICO,
    --'' AS RESTRICAO, 
    CLIENTE.NOME,
    CASE WHEN CLIENTE.CPF = '___.___.___-__' THEN CLIENTE.CGC ELSE CLIENTE.CPF END AS CPF_CNPJ,
    YEAR(EVENTO.DATA) AS MES_RESULTADO,
    MONTH(EVENTO.DATA) AS MES_RESULTADO,
    DAY(EVENTO.DATA) AS DIA_RESULTADO,
    YEAR(EVENTO.DATA) AS ANO_IMPORTACAO,
    MONTH(EVENTO.DATA) AS MES_IMPORTACAO,
    DAY(EVENTO.DATA) AS DIA_IMPORTACAO,
    CASE WHEN EVENTO.TIPO_PROCESSO_ID = 0 THEN 'NÃO CONTATADO' 
   ELSE BV_RELAGRUPAMENTO.BV_RELAGRUPAMENTO 
  END AS AGRUPAMENTO,
       CASE WHEN EVENTO.TIPO_PROCESSO_ID = 0 THEN 'NÃO CONTATADO' 
   WHEN TIPO_PROCESSO.COD_FIM = 6100 THEN 'OUTROS'
   ELSE TIPO_PROCESSO.TITULO 
  END AS FINALIZACAO,
  --OPERADOR.OPERADOR_NAME,
  --EQUIPE.EQUIPE,
  'CREDPRT_RECUP_RECEPT' AS LISTA,
  'CREDPRT_RECUP_RECEPT' AS CAMPANHA,
  '1' AS QTDE,
  '14 - N/A' AS [FAIXA_PREMIO_MAILING],
  0 AS [PREMIO_MAILING]

FROM 
(
SELECT MAX(EVENTO.EVENTO_ID) AS EVENTO_ID,
  EVENTO.CLIENTE_ID,
  EVENTO.DATA
FROM EVENTO
WHERE EVENTO.ORIGEM_ID IN (576,577,593) -- ORIGENS CREDITO PROTEGIDO - TODAS
   AND EVENTO.COD_FIM = 7100 -- SOMENTE COMERCIALIZACAO
   AND EVENTO.MAILING_ID = 0
   AND EVENTO.DATA BETWEEN @DATA_INI_RCP AND GETDATE()-1
   AND EVENTO.ORIGEM_ID NOT IN (701,839,874,875,878,898)
GROUP BY EVENTO.CLIENTE_ID, EVENTO.DATA
)#TB
	INNER JOIN EVENTO (NOLOCK)    ON (#TB.EVENTO_ID = EVENTO.EVENTO_ID)
	LEFT JOIN CLIENTE (NOLOCK)    ON (EVENTO.CLIENTE_ID = CLIENTE.CLIENTE_ID)
	LEFT JOIN TIPO_PROCESSO (NOLOCK)  ON (EVENTO.TIPO_PROCESSO_ID = TIPO_PROCESSO.TIPO_PROCESSO_ID)
	--LEFT JOIN OPERADOR (NOLOCK)    ON (EVENTO.OPERADOR_ID = OPERADOR.OPERADOR_ID)
	--LEFT JOIN EQUIPE (NOLOCK)    ON (OPERADOR.EQUIPE_ID = EQUIPE.EQUIPE_ID)
	LEFT JOIN BV_RELAGRUPAMENTO (NOLOCK) ON (TIPO_PROCESSO.RELATORIO_AGRUPAMENTO = BV_RELAGRUPAMENTO.BV_RELAGRUPAMENTO_ID)
	) #TB
	LEFT JOIN EVENTO (NOLOCK)   ON (#TB.EVENTO_ID = EVENTO.EVENTO_ID)
	INNER JOIN ORIGEM (NOLOCK)   ON (#TB.ORIGEM_ID = ORIGEM.ORIGEM_ID)
	LEFT JOIN TIPO_ORIGEM (NOLOCK)  ON (ORIGEM.TIPO = TIPO_ORIGEM.TIPO_ORIGEM_ID)
	LEFT JOIN EVENTO_AUX EA1 (NOLOCK) ON (EVENTO.EVENTO_ID = EA1.EVENTO_ID AND EA1.CAMPO_AUX_ID IN (SELECT CAMPO_AUX_ID FROM CAMPO_AUX WHERE CODIGO IN ('PRMBRUTO','104002'))) -- PREMIO
	LEFT JOIN EVENTO_AUX EA2 (NOLOCK) ON (EVENTO.EVENTO_ID = EA2.EVENTO_ID AND EA2.CAMPO_AUX_ID IN (SELECT CAMPO_AUX_ID FROM CAMPO_AUX WHERE CODIGO IN ('PROPOSTA'))) -- PROPOSTA
	LEFT JOIN #PRE (NOLOCK) ON (#TB.MAILING_ID = #PRE.MAILING_ID)

SELECT
 PR.[STATUS],
 'TLV 4' AS [SISTEMA],
 PR.OPERACAO,
 PR.TIPO_CANAL,
 PR.[CANAL CONTATO],
 PR.MAILING_ID,
 PR.EVENTO_ID,
 PR.ORIGEM_ID,
 PR.CLIENTE_ID,
 PR.PUBLICO,
 --PR.RESTRICAO,
 PR.NOME,
 PR.CPF_CNPJ,
 PR.ANO_RESULTADO,
 PR.MES_RESULTADO,
 PR.DIA_RESULTADO,
 PR.ANO_IMPORTACAO,
 PR.MES_IMPORTACAO,
 PR.DIA_IMPORTACAO,
 PR.AGRUPAMENTO,
 PR.FINALIZACAO,
 CASE WHEN OP.OPERADOR_NAME = '' THEN 'SEM CONTATO' ELSE OP.OPERADOR_NAME END AS OPERADOR_NAME,
 CASE WHEN OP.EQUIPE = '' THEN 'SEM CONTATO' ELSE OP.EQUIPE END AS EQUIPE,
 PR.LISTA,
 PR.CAMPANHA,
 PR.QTDE,
 PR.FAIXA_PREMIO_MAILING,
 PR.PREMIO_MAILING,
 PR.PREMIO,
 PR.PROPOSTA,
 PR.CPC,
 PR.[QTDE_CONTRATACOES],
 0 AS [QTDE_LIGAÇÕES]

FROM
 #PROD AS PR
 LEFT JOIN #OPE AS OP ON PR.EVENTO_ID = OP.EVENTO_ID

 WHERE PR.LISTA = 'CRED PROTEGIDO-RECUPERACAO PARCELAS'

 UNION ALL

 SELECT
 PR.[STATUS],
 'TLV 4' AS [SISTEMA],
 PR.OPERACAO,
 PR.TIPO_CANAL,
 PR.[CANAL CONTATO],
 PR.MAILING_ID,
 PR.EVENTO_ID,
 PR.ORIGEM_ID,
 PR.CLIENTE_ID,
 PR.PUBLICO,
 --PR.RESTRICAO,
 PR.NOME,
 PR.CPF_CNPJ,
 PR.ANO_RESULTADO,
 PR.MES_RESULTADO,
 PR.DIA_RESULTADO,
 PR.ANO_IMPORTACAO,
 PR.MES_IMPORTACAO,
 PR.DIA_IMPORTACAO,
 PR.AGRUPAMENTO,
 PR.FINALIZACAO,
 CASE WHEN OP.OPERADOR_NAME = '' THEN 'SEM CONTATO' ELSE OP.OPERADOR_NAME END AS OPERADOR_NAME,
 CASE WHEN OP.EQUIPE = '' THEN 'SEM CONTATO' ELSE OP.EQUIPE END AS EQUIPE,
 PR.LISTA,
 PR.CAMPANHA,
 PR.QTDE,
 PR.FAIXA_PREMIO_MAILING,
 PR.PREMIO_MAILING,
 PR.PREMIO,
 PR.PROPOSTA,
 PR.CPC,
 PR.[QTDE_CONTRATACOES],
 0 AS [QTDE_LIGAÇÕES]

FROM
 #PROD AS PR
 LEFT JOIN #OPE AS OP ON PR.EVENTO_ID = OP.EVENTO_ID

 WHERE PR.LISTA = 'CREDPRT_RECUP_RECEPT' AND MES_IMPORTACAO > 6
