--Exemplo de extração de Receita, com CPF do cliente

SELECT CL.CLIENTE_COD, TIPO_PROCESSO, CONVERT(FLOAT,LD2.CAMPO_TXT,0) AS PREMIO_BASE
FROM MAILING ML (NOLOCK)
	INNER JOIN CLIENTE CL (NOLOCK) ON ML.CLIENTE_ID = CL.CLIENTE_ID
	INNER JOIN TIPO_PROCESSO TP (NOLOCK) ON ML.TIPO_PROCESSO_ID = TP.TIPO_PROCESSO_ID
	INNER JOIN LISTA_DET LD (NOLOCK) ON ML.LISTA_DET_ID = LD.LISTA_DET_ID
	INNER JOIN LISTA_DET_AUX LD2 (NOLOCK) ON (LD.LISTA_DET_ID = LD2.LISTA_DET_ID AND LD2.CAMPO_AUX_ID IN 
		(SELECT CAMPO_AUX_ID FROM CAMPO_AUX WHERE CAMPO_AUX = 'CP_SEQ'))
WHERE ML.LISTA_ID IN (4195,4214)
ORDER BY LD2.CAMPO_TXT DESC


